spring:

  config:
    import: file:env.properties

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: true

logging:
  level:
    org:
      springframework:
        security: trace